### ISSUE TITLE
"see list" pop-up link not working correctly

### ISSUE THREAD

**Issue by MikeTrizna** [biocodellc/biscicol-fims#13]
I tried validating a spreadsheet, and received a warning that one of my columns contained values that were not in my configuration's controlled vocabulary. It looks like this:
![image](https://cloud.githubusercontent.com/assets/472677/14318119/6245c706-fbd9-11e5-9141-405044012206.png)

However, when I click the "see list" portion of that warning message, it only expands/contracts the message to show all values that failed validation, rather than showing me the list.
![image](http://i.giphy.com/xTiQyfrTpfxyKLIEaA.gif)

I'm using Chrome on a Windows 7 machine.

**Comment by rodney757** [comment]
this is fixed in commit 81d9cc2

**Comment by MikeTrizna** [comment]
Thanks for addressing this, @rodney757.  

Is there a delay before the committed version of the web page is deployed to the server? I just tested it on Firefox and Chrome, and the validation list still doesn't pop up.

**Comment by jdeck88** [comment]
process is usually:
make fixes, test locally, commit to git, git pull and deploy to test
server, run tests on test server and then deploy to production server.
Changes should be live in about 5 minutes (i'm waiting now on the war file
 to be sent to server right now)

Oh--- and you may need to force-reload your cache to get latest javascript.

John

On Thu, Apr 7, 2016 at 7:20 AM, Mike Trizna notifications@github.com
wrote:

> Thanks for addressing this, @rodney757 https://github.com/rodney757.
> 
> Is there a delay before the committed version of the web page is deployed
> to the server? I just tested it on Firefox and Chrome, and the validation
> list still doesn't pop up.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/13#issuecomment-206927693

## 

John Deck
(541) 914-4739
